# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NameGame' do
  pod 'DeepDiff'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NameGame

  target 'NameGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NameGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
